services:
  pg-docker:
    image: postgres:14-alpine
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5432:5432   # 5432 -> container 5433 -> local
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data